lint:
  rules:
    add:
      - MESSAGE_NAMES_UPPER_CAMEL_CASE
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      - INDENT
      - ORDER
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - PROTO3_FIELDS_AVOID_REQUIRED
      - PROTO3_GROUPS_AVOID
      - RPC_NAMES_UPPER_CAMEL_CASE
      - SERVICE_NAMES_END_WITH
      - PACKAGE_NAME_LOWER_CASE
      - QUOTE_CONSISTENT
      - SYNTAX_CONSISTENT
