name: Build And Publish Docker Image
on:
  schedule:
    - cron: "3,18,33,48 * * * *"
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=schedule,pattern=nightly
            type=schedule,pattern={{date 'YYYY'}}
            type=schedule,pattern={{date 'YYYYMM'}}
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=schedule,pattern={{date 'YYYYMMDDHH'}}
            type=schedule,pattern={{date 'YYYYMMDDHHmm'}}
            type=schedule,pattern={{date 'YYYYMMDDHHmmss'}}
          labels: |
            maintainer=xeptore
            org.opencontainers.image.authors=xeptore
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/v1.') }}
            prefix=,onlatest=false
            suffix=,onlatest=false
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build_and_push
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          context: .
          file: build/Dockerfile
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
